plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

title: Fabula ex Machina
description: Fabula ex Machina means literally 'fable from the machine'.